classdef BrakingDatasetGenerator < handle
    % BRAKINGDATASETGENERATOR Genere un dataset temporel de freinage sain.
    %
    % Le generateur est specialise pour le premier modele predictif :
    %   - les quatre capteurs restent sains ;
    %   - le frein est strictement positif des t = 0 ;
    %   - le braquage est toujours non nul ;
    %   - la vitesse initiale est comprise entre 40 et 100 km/h ;
    %   - toutes les simulations ont la meme duree et la meme frequence.
    %
    % Les sorties sont ecrites progressivement dans un CSV compact. Cette
    % strategie permet de lancer 30 000 simulations sans conserver les
    % millions de lignes du dataset complet en memoire.
    %
    % Exemple :
    %   generator = BrakingDatasetGenerator();
    %   [csvPath, manifestPath] = generator.generate();
    %
    % Par defaut, generate() execute 30 000 simulations de 5 secondes.

    properties (SetAccess = private)
        baseConfigPath (1,1) string
        outputFolder (1,1) string
        randomSeed (1,1) double
        steeringRatio (1,1) double
        commandStepSeconds (1,1) double
    end

    properties (Constant, Access = private)
        PHENOMENA = [ ...
            "normal_braking", "sliding", ...
            "wheel_lock", "random_braking"]
        DEFAULT_DISTRIBUTION = [0.30, 0.30, 0.30, 0.10]
        WHEELS = ["FL", "FR", "RL", "RR"]
        MINIMUM_STEERING_WHEEL_DEG = 10
        SLIDING_THRESHOLD = 0.05
    end

    methods
        function obj = BrakingDatasetGenerator(baseConfigPath, ...
                outputFolder, randomSeed, steeringRatio, ...
                commandStepSeconds)
            arguments
                baseConfigPath (1,1) string = ""
                outputFolder (1,1) string = ""
                randomSeed (1,1) double ...
                    {mustBeNonnegative, mustBeInteger} = 30000
                steeringRatio (1,1) double {mustBePositive} = 15
                commandStepSeconds (1,1) double {mustBePositive} = 0.05
            end

            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            if strlength(baseConfigPath) == 0
                baseConfigPath = fullfile(projectRoot, "scenarios", ...
                    "scenario_physics_dataset.json");
            end
            if strlength(outputFolder) == 0
                outputFolder = fullfile(projectRoot, "simulation_results");
            end

            assert(isfile(baseConfigPath), ...
                "Configuration physique de base introuvable : %s", ...
                baseConfigPath);

            obj.baseConfigPath = baseConfigPath;
            obj.outputFolder = outputFolder;
            obj.randomSeed = randomSeed;
            obj.steeringRatio = steeringRatio;
            obj.commandStepSeconds = commandStepSeconds;
        end

        function [outputPath, manifestPath, manifest] = generate(obj, ...
                numberOfSimulations, durationSeconds, options)
            arguments
                obj
                numberOfSimulations (1,1) double ...
                    {mustBePositive, mustBeInteger} = 30000
                durationSeconds (1,1) double {mustBePositive} = 5.0
                options.ClassifyObserved (1,1) logical = true
                options.ChunkSize (1,1) double ...
                    {mustBePositive, mustBeInteger} = 25
                options.ProgressEvery (1,1) double ...
                    {mustBePositive, mustBeInteger} = 100
                options.InjectIntermittentLoss (1,1) logical = false
                options.FaultStartRangeSeconds (1,2) double ...
                    {mustBeNonnegative} = [1.5, 2.0]
                options.FaultDurationRangeSeconds (1,2) double ...
                    {mustBePositive} = [1.5, 2.0]
                options.FaultSeverityLevels (1,:) double = ...
                    [0.25, 0.50, 0.75, 1.00]
                options.FaultDropoutProbability (1,1) double = 0.50
            end

            template = jsondecode(fileread(obj.baseConfigPath));
            dt = template.simulation.dt;
            ecuSampleTime = template.ecu.sampleTime;
            assert(abs(dt - ecuSampleTime) < 1e-12, ...
                "Pour ce dataset, simulation.dt et ecu.sampleTime doivent etre egaux.");

            numberOfSteps = floor(durationSeconds / dt);
            assert(durationSeconds >= 1.0 && numberOfSteps >= 25, ...
                "Une simulation doit durer au moins une seconde.");
            assert(abs(numberOfSteps * dt - durationSeconds) < 1e-9, ...
                "La duree doit etre un multiple exact du pas de simulation.");
            assert(obj.commandStepSeconds >= dt, ...
                "Le pas de commande doit etre superieur ou egal au pas de simulation.");
            if options.InjectIntermittentLoss
                obj.validateFaultOptions(durationSeconds, options);
            end

            phenomena = obj.makePhenomenonSchedule(numberOfSimulations);
            if ~isfolder(obj.outputFolder)
                mkdir(obj.outputFolder);
            end

            timestamp = string(datetime("now", ...
                "Format", "yyyyMMdd_HHmmss_SSS"));
            if options.InjectIntermittentLoss
                datasetPrefix = "abs_faulty_braking_dataset_";
                manifestPrefix = "abs_faulty_braking_manifest_";
            else
                datasetPrefix = "abs_healthy_braking_dataset_";
                manifestPrefix = "abs_healthy_braking_manifest_";
            end
            outputPath = fullfile(obj.outputFolder, ...
                datasetPrefix + timestamp + ".csv");
            manifestPath = fullfile(obj.outputFolder, ...
                manifestPrefix + timestamp + ".csv");

            manifestRows = repmat(obj.emptyManifestRow(), ...
                numberOfSimulations, 1);
            dataChunk = table();
            manifestChunk = table();
            firstDataWrite = true;
            firstManifestWrite = true;

            for simulationIndex = 1:numberOfSimulations
                phenomenon = phenomena(simulationIndex);
                concreteSeed = obj.randomSeed + simulationIndex - 1;
                stream = RandStream("mt19937ar", "Seed", concreteSeed);

                [rawConfig, generated] = obj.buildConcreteConfig( ...
                    template, phenomenon, durationSeconds, ...
                    concreteSeed, simulationIndex, stream);
                if options.InjectIntermittentLoss
                    [rawConfig, generated] = obj.addIntermittentLossFault( ...
                        rawConfig, generated, durationSeconds, ...
                        simulationIndex, stream, options);
                end

                configPath = obj.writeTemporaryConfig(rawConfig);
                cleanup = onCleanup( ...
                    @()obj.deleteTemporaryConfig(configPath));
                config = SimulationConfig(configPath);
                controller = SimulationController(config);
                logger = SimulationDataLogger(numberOfSteps, config);

                for stepIndex = 1:numberOfSteps
                    commandTime = (stepIndex - 1) * dt;
                    logger.append(controller.stepAt(commandTime));
                end

                fullResult = logger.toTable();
                compactResult = obj.makeCompactResult( ...
                    fullResult, simulationIndex, phenomenon, ...
                    concreteSeed, generated, options.ClassifyObserved);
                dataChunk = obj.appendTable(dataChunk, compactResult);

                manifestRows(simulationIndex) = obj.buildManifestRow( ...
                    simulationIndex, phenomenon, concreteSeed, ...
                    generated, fullResult, options.ClassifyObserved);
                manifestChunk = obj.appendTable(manifestChunk, ...
                    struct2table(manifestRows(simulationIndex)));
                clear cleanup

                flushChunk = height(dataChunk) >= ...
                    options.ChunkSize * numberOfSteps;
                if flushChunk || simulationIndex == numberOfSimulations
                    obj.writeTableChunk(dataChunk, outputPath, firstDataWrite);
                    firstDataWrite = false;
                    dataChunk = table();
                    obj.writeTableChunk(manifestChunk, ...
                        manifestPath, firstManifestWrite);
                    firstManifestWrite = false;
                    manifestChunk = table();
                end

                if mod(simulationIndex, options.ProgressEvery) == 0 || ...
                        simulationIndex == numberOfSimulations
                    fprintf("Simulations de freinage : %d/%d.\n", ...
                        simulationIndex, numberOfSimulations);
                end
            end

            manifest = struct2table(manifestRows);

            fprintf("Dataset termine : %d simulations, %d lignes.\n", ...
                numberOfSimulations, numberOfSimulations * numberOfSteps);
            fprintf("CSV temporel : %s\n", outputPath);
            fprintf("Manifeste : %s\n", manifestPath);
        end
    end

    methods (Access = private)
        function phenomena = makePhenomenonSchedule(obj, totalCount)
            exactCounts = obj.DEFAULT_DISTRIBUTION * totalCount;
            counts = floor(exactCounts);
            remaining = totalCount - sum(counts);
            [~, order] = sort(exactCounts - counts, "descend");
            counts(order(1:remaining)) = counts(order(1:remaining)) + 1;

            phenomena = strings(1, totalCount);
            cursor = 1;
            for index = 1:numel(obj.PHENOMENA)
                nextCursor = cursor + counts(index);
                phenomena(cursor:nextCursor - 1) = ...
                    obj.PHENOMENA(index);
                cursor = nextCursor;
            end

            stream = RandStream("mt19937ar", "Seed", obj.randomSeed);
            phenomena = phenomena(randperm(stream, totalCount));
        end

        function [raw, generated] = buildConcreteConfig(obj, template, ...
                phenomenon, duration, seed, simulationIndex, stream)
            raw = template;
            raw.meta.name = sprintf("healthy_braking_%s_%06d", ...
                phenomenon, seed);
            raw.meta.description = sprintf( ...
                "Freinage sain genere : %s", phenomenon);
            raw.meta.seed = seed;
            raw.meta.requestedPhenomenon = char(phenomenon);
            raw.simulation.duration = duration;
            raw.sensorErrors.randomSeed = seed;
            if isfield(raw, "faults")
                raw = rmfield(raw, "faults");
            end

            initialSpeedKmh = obj.stratifiedInitialSpeed( ...
                simulationIndex, stream);
            [brakeRecipe, muRoad] = obj.makeBrakeRecipe( ...
                phenomenon, duration, stream);
            steeringRecipe = obj.makeSteeringRecipe( ...
                initialSpeedKmh, duration, stream);

            segments = obj.makeCommandSegments( ...
                duration, brakeRecipe, steeringRecipe);
            assert(segments(1).brake > 0, ...
                "Le frein doit etre actif des le premier segment.");
            initialSteeringWheelDeg = rad2deg( ...
                segments(1).steering) * obj.steeringRatio;
            assert(abs(initialSteeringWheelDeg) >= ...
                obj.MINIMUM_STEERING_WHEEL_DEG - 1e-9, ...
                "Le braquage initial doit respecter la borne minimale.");

            raw.vehicle.muRoad = muRoad;
            raw.road.muRoad = muRoad;
            raw.scenario.type = "generated_braking_segments";
            raw.scenario.initialSpeed_kmh = initialSpeedKmh;
            raw.scenario.defaultCommand = struct( ...
                "throttle", 0, "brake", segments(end).brake, ...
                "steering", segments(end).steering);
            raw.scenario.segments = segments;

            raw.meta.brakeProfile = char(brakeRecipe.name);
            raw.meta.steeringProfile = char(steeringRecipe.name);
            raw.meta.generatedMuRoad = muRoad;
            raw.meta.steeringRatio = obj.steeringRatio;

            brakeValues = [segments.brake];
            steeringWheelValues = ...
                rad2deg([segments.steering]) * obj.steeringRatio;
            generated = struct( ...
                "brakeProfile", brakeRecipe.name, ...
                "steeringProfile", steeringRecipe.name, ...
                "initialSpeedKmh", initialSpeedKmh, ...
                "muRoad", muRoad, ...
                "minimumBrake", min(brakeValues), ...
                "maximumBrake", max(brakeValues), ...
                "minimumAbsSteeringWheelDeg", ...
                    min(abs(steeringWheelValues)), ...
                "maximumAbsSteeringWheelDeg", ...
                    max(abs(steeringWheelValues)), ...
                "steeringDirection", sign(steeringWheelValues(1)), ...
                "faultWheel", "none", ...
                "faultType", "none", ...
                "faultStartSeconds", NaN, ...
                "faultEndSeconds", NaN, ...
                "faultSeverity", 0, ...
                "faultDropoutProbability", 0, ...
                "effectiveDropoutProbability", 0);
        end

        function validateFaultOptions(~, duration, options)
            assert(options.FaultStartRangeSeconds(1) <= ...
                options.FaultStartRangeSeconds(2), ...
                "FaultStartRangeSeconds doit etre croissant.");
            assert(options.FaultDurationRangeSeconds(1) <= ...
                options.FaultDurationRangeSeconds(2), ...
                "FaultDurationRangeSeconds doit etre croissant.");
            assert(options.FaultStartRangeSeconds(2) < duration, ...
                "Le defaut doit commencer avant la fin de la simulation.");
            assert(~isempty(options.FaultSeverityLevels) && ...
                all(isfinite(options.FaultSeverityLevels)) && ...
                all(options.FaultSeverityLevels > 0) && ...
                all(options.FaultSeverityLevels <= 1), ...
                "Les severites doivent appartenir a ]0,1].");
            assert(options.FaultDropoutProbability > 0 && ...
                options.FaultDropoutProbability <= 1, ...
                "FaultDropoutProbability doit appartenir a ]0,1].");
        end

        function [raw, generated] = addIntermittentLossFault(obj, raw, ...
                generated, duration, simulationIndex, stream, options)
            wheelIndex = mod(simulationIndex - 1, numel(obj.WHEELS)) + 1;
            wheel = obj.WHEELS(wheelIndex);
            severityIndex = mod( ...
                floor((simulationIndex - 1) / numel(obj.WHEELS)), ...
                numel(options.FaultSeverityLevels)) + 1;
            severity = options.FaultSeverityLevels(severityIndex);

            startSeconds = obj.uniform(stream, ...
                options.FaultStartRangeSeconds(1), ...
                options.FaultStartRangeSeconds(2));
            faultDuration = obj.uniform(stream, ...
                options.FaultDurationRangeSeconds(1), ...
                options.FaultDurationRangeSeconds(2));
            endSeconds = min(duration, startSeconds + faultDuration);
            assert(endSeconds > startSeconds, ...
                "La duree concrete du defaut doit etre positive.");

            raw.faults = struct( ...
                "wheel", char(wheel), ...
                "type", "intermittent_loss", ...
                "startTime", startSeconds, ...
                "endTime", endSeconds, ...
                "severity", severity, ...
                "params", struct( ...
                    "dropoutProbability", ...
                    options.FaultDropoutProbability));
            raw.meta.name = sprintf("faulty_braking_%s_%06d", ...
                string(raw.meta.requestedPhenomenon), raw.meta.seed);
            raw.meta.description = sprintf( ...
                "Freinage avec pertes intermittentes %s : %s", ...
                wheel, string(raw.meta.requestedPhenomenon));

            generated.faultWheel = wheel;
            generated.faultType = "intermittent_loss";
            generated.faultStartSeconds = startSeconds;
            generated.faultEndSeconds = endSeconds;
            generated.faultSeverity = severity;
            generated.faultDropoutProbability = ...
                options.FaultDropoutProbability;
            generated.effectiveDropoutProbability = min(1, ...
                severity * options.FaultDropoutProbability);
        end

        function speed = stratifiedInitialSpeed(~, simulationIndex, stream)
            binIndex = mod(simulationIndex - 1, 6);
            lower = 40 + 10 * binIndex;
            upper = lower + 10;
            speed = lower + (upper - lower) * rand(stream);
            speed = min(speed, 100);
        end

        function [recipe, muRoad] = makeBrakeRecipe(obj, ...
                phenomenon, duration, stream)
            switch phenomenon
                case "normal_braking"
                    muRoad = obj.uniform(stream, 0.70, 1.00);
                    levels = [0.05, 0.10, 0.15];
                    startValue = obj.pick(stream, levels);
                    endValue = obj.pick(stream, levels);
                    allowedProfiles = ["constant", "ramp_up", "ramp_down"];

                case "sliding"
                    muRoad = obj.uniform(stream, 0.30, 0.55);
                    startValue = obj.uniform(stream, 0.10, 0.16);
                    endValue = obj.uniform(stream, 0.16, 0.25);
                    allowedProfiles = ["short_pulse", "ramp_pulse"];

                case "wheel_lock"
                    muRoad = obj.uniform(stream, 0.06, 0.18);
                    levels = [0.70, 0.85, 1.00];
                    startValue = obj.pick(stream, [0.20, 0.35, 0.50]);
                    endValue = obj.pick(stream, levels);
                    allowedProfiles = ["constant", "ramp_up"];
                    if rand(stream) < 0.55
                        startValue = endValue;
                    end

                case "random_braking"
                    muRoad = obj.uniform(stream, 0.10, 1.00);
                    levels = 0.10:0.10:1.00;
                    startValue = obj.pick(stream, levels);
                    endValue = obj.pick(stream, levels);
                    allowedProfiles = [ ...
                        "constant", "ramp_up", "ramp_down", ...
                        "strong_then_release", "mixed"];

                otherwise
                    error("BrakingDatasetGenerator:unsupportedPhenomenon", ...
                        "Phenomenon non supporte : %s.", phenomenon);
            end

            profile = obj.pick(stream, allowedProfiles);
            if profile == "ramp_up" && endValue < startValue
                values = sort([startValue, endValue]);
                startValue = values(1);
                endValue = values(2);
            elseif profile == "ramp_down" && endValue > startValue
                values = sort([startValue, endValue], "descend");
                startValue = values(1);
                endValue = values(2);
            end

            rampDuration = obj.uniform(stream, ...
                0.20 * duration, 0.55 * duration);
            switch profile
                case "constant"
                    values = [endValue, endValue];
                    times = [0, duration];

                case {"ramp_up", "ramp_down"}
                    values = [startValue, endValue, endValue];
                    times = [0, rampDuration, duration];

                case "strong_then_release"
                    high = max(startValue, endValue);
                    low = max(0.02, min(startValue, endValue) * 0.35);
                    values = [high, high, low, low];
                    times = [0, 0.35 * duration, ...
                        0.60 * duration, duration];

                case "mixed"
                    middle = obj.pick(stream, 0.10:0.10:1.00);
                    final = obj.pick(stream, 0.05:0.05:0.60);
                    values = [startValue, middle, endValue, final];
                    times = [0, 0.30 * duration, ...
                        0.65 * duration, duration];

                case "short_pulse"
                    pulseEnd = min(0.40, 0.20 * duration);
                    releaseEnd = pulseEnd + 0.10;
                    high = max(startValue, endValue);
                    values = [high, high, 0.02, 0.02];
                    times = [0, pulseEnd, releaseEnd, duration];

                case "ramp_pulse"
                    rampEnd = min(0.15, 0.08 * duration);
                    pulseEnd = min(0.40, 0.20 * duration);
                    releaseEnd = pulseEnd + 0.10;
                    values = [startValue, endValue, ...
                        endValue, 0.02, 0.02];
                    times = [0, rampEnd, pulseEnd, ...
                        releaseEnd, duration];
            end

            recipe = struct( ...
                "name", profile, ...
                "times", times, ...
                "values", values);
        end

        function recipe = makeSteeringRecipe(obj, initialSpeedKmh, ...
                duration, stream)
            if initialSpeedKmh < 60
                maximumAngle = 60;
            elseif initialSpeedKmh < 80
                maximumAngle = 35;
            else
                maximumAngle = 20;
            end

            signValue = 2 * (rand(stream) >= 0.5) - 1;
            firstMagnitude = obj.uniform(stream, ...
                obj.MINIMUM_STEERING_WHEEL_DEG, maximumAngle);
            secondMagnitude = obj.uniform(stream, ...
                obj.MINIMUM_STEERING_WHEEL_DEG, maximumAngle);
            profile = obj.pick(stream, ...
                ["constant", "increase_turn", "decrease_turn"]);

            switch profile
                case "constant"
                    values = signValue * [firstMagnitude, firstMagnitude];
                    times = [0, duration];

                case "increase_turn"
                    magnitudes = sort([firstMagnitude, secondMagnitude]);
                    values = signValue * ...
                        [magnitudes(1), magnitudes(2), magnitudes(2)];
                    times = [0, 0.55 * duration, duration];

                case "decrease_turn"
                    magnitudes = sort([firstMagnitude, secondMagnitude], ...
                        "descend");
                    values = signValue * ...
                        [magnitudes(1), magnitudes(2), magnitudes(2)];
                    times = [0, 0.55 * duration, duration];
            end

            recipe = struct( ...
                "name", profile, ...
                "times", times, ...
                "wheelAngleValuesDeg", values);
        end

        function segments = makeCommandSegments(obj, duration, ...
                brakeRecipe, steeringRecipe)
            numberOfSegments = ceil(duration / obj.commandStepSeconds);
            segments = repmat(struct( ...
                "startTime", 0, "endTime", 0, ...
                "throttle", 0, "brake", 0, "steering", 0), ...
                numberOfSegments, 1);

            for index = 1:numberOfSegments
                startTime = (index - 1) * obj.commandStepSeconds;
                endTime = min(duration, ...
                    index * obj.commandStepSeconds);
                brake = interp1(brakeRecipe.times, ...
                    brakeRecipe.values, startTime, "linear");
                steeringWheelDeg = interp1(steeringRecipe.times, ...
                    steeringRecipe.wheelAngleValuesDeg, ...
                    startTime, "linear");
                roadWheelRad = deg2rad( ...
                    steeringWheelDeg / obj.steeringRatio);

                segments(index) = struct( ...
                    "startTime", startTime, ...
                    "endTime", endTime, ...
                    "throttle", 0, ...
                    "brake", min(1, max(0, brake)), ...
                    "steering", roadWheelRad);
            end
        end

        function compact = makeCompactResult(obj, result, simulationIndex, ...
                phenomenon, seed, generated, classifyObserved)
            n = height(result);
            observed = obj.classifyRows(result, classifyObserved);
            steeringWheelDeg = ...
                rad2deg(result.steering_rad) * obj.steeringRatio;

            compact = table( ...
                repmat(simulationIndex, n, 1), ...
                repmat(seed, n, 1), ...
                repmat(phenomenon, n, 1), ...
                observed, ...
                repmat(string(generated.brakeProfile), n, 1), ...
                repmat(string(generated.steeringProfile), n, 1), ...
                repmat(generated.initialSpeedKmh, n, 1), ...
                repmat(generated.muRoad, n, 1), ...
                result.time_s, result.brake, ...
                steeringWheelDeg, result.steering_rad, ...
                result.vehicle_speed_mps, ...
                'VariableNames', { ...
                'simulation_id', 'simulation_seed', ...
                'requested_phenomenon', 'observed_phenomenon', ...
                'brake_profile', 'steering_profile', ...
                'initial_speed_kmh', 'mu_road', ...
                'time_s', 'brake', 'steering_wheel_angle_deg', ...
                'road_wheel_angle_rad', 'vehicle_speed_mps'});

            for wheel = obj.WHEELS
                compact.("wheel_peripheral_speed_" + wheel + "_mps") = ...
                    result.("wheel_peripheral_speed_" + wheel + "_mps");
                compact.("wheel_speed_ecu_" + wheel + "_mps") = ...
                    result.("wheel_speed_ecu_" + wheel + "_mps");
                compact.("error_ecu_minus_true_" + wheel + "_mps") = ...
                    result.("error_ecu_minus_true_" + wheel + "_mps");
                compact.("ecu_valid_" + wheel) = ...
                    result.("ecu_valid_" + wheel);
                compact.("ecu_status_" + wheel) = ...
                    result.("ecu_status_" + wheel);
                compact.("wheel_slip_ratio_" + wheel) = ...
                    result.("wheel_slip_ratio_" + wheel);
                compact.("wheel_locked_" + wheel) = ...
                    result.("wheel_locked_" + wheel);
                compact.("dropped_edges_" + wheel) = ...
                    result.("dropped_edges_" + wheel);
                compact.("fault_active_" + wheel) = ...
                    result.("fault_active_" + wheel);
                compact.("fault_type_" + wheel) = ...
                    result.("fault_type_" + wheel);
                compact.("fault_severity_" + wheel) = ...
                    result.("fault_severity_" + wheel);
            end
        end

        function observed = classifyRows(obj, result, enabled)
            n = height(result);
            if ~enabled
                observed = repmat("not_computed", n, 1);
                return;
            end

            slipNames = "wheel_slip_ratio_" + obj.WHEELS;
            lockNames = "wheel_locked_" + obj.WHEELS;
            slip = result{:, cellstr(slipNames)};
            locked = result{:, cellstr(lockNames)};

            observed = repmat("normal_braking", n, 1);
            observed(max(abs(slip), [], 2) >= ...
                obj.SLIDING_THRESHOLD) = "sliding";
            observed(any(locked, 2)) = "wheel_lock";
        end

        function row = emptyManifestRow(~)
            row = struct( ...
                "simulation_id", 0, ...
                "requested_phenomenon", "", ...
                "observed_phenomenon", "", ...
                "seed", 0, ...
                "brake_profile", "", ...
                "steering_profile", "", ...
                "initial_speed_kmh", 0, ...
                "mu_road", 0, ...
                "minimum_brake", 0, ...
                "maximum_brake", 0, ...
                "minimum_abs_steering_wheel_deg", 0, ...
                "maximum_abs_steering_wheel_deg", 0, ...
                "maximum_abs_slip", 0, ...
                "any_wheel_locked", false, ...
                "fault_wheel", "none", ...
                "fault_type", "none", ...
                "fault_start_s", NaN, ...
                "fault_end_s", NaN, ...
                "fault_severity", 0, ...
                "dropout_probability", 0, ...
                "effective_dropout_probability", 0, ...
                "dropped_edge_count", 0);
        end

        function row = buildManifestRow(obj, simulationIndex, ...
                requestedPhenomenon, seed, generated, result, ...
                classifyObserved)
            slipNames = "wheel_slip_ratio_" + obj.WHEELS;
            lockNames = "wheel_locked_" + obj.WHEELS;
            slip = result{:, cellstr(slipNames)};
            locked = result{:, cellstr(lockNames)};
            maximumSlip = max(abs(slip), [], "all");
            anyLocked = any(locked, "all");
            droppedNames = "dropped_edges_" + obj.WHEELS;
            droppedEdgeCount = sum( ...
                result{:, cellstr(droppedNames)}, "all");

            if ~classifyObserved
                observed = "not_computed";
            elseif anyLocked
                observed = "wheel_lock";
            elseif maximumSlip >= obj.SLIDING_THRESHOLD
                observed = "sliding";
            else
                observed = "normal_braking";
            end

            row = struct( ...
                "simulation_id", simulationIndex, ...
                "requested_phenomenon", requestedPhenomenon, ...
                "observed_phenomenon", observed, ...
                "seed", seed, ...
                "brake_profile", string(generated.brakeProfile), ...
                "steering_profile", string(generated.steeringProfile), ...
                "initial_speed_kmh", generated.initialSpeedKmh, ...
                "mu_road", generated.muRoad, ...
                "minimum_brake", generated.minimumBrake, ...
                "maximum_brake", generated.maximumBrake, ...
                "minimum_abs_steering_wheel_deg", ...
                    generated.minimumAbsSteeringWheelDeg, ...
                "maximum_abs_steering_wheel_deg", ...
                    generated.maximumAbsSteeringWheelDeg, ...
                "maximum_abs_slip", maximumSlip, ...
                "any_wheel_locked", anyLocked, ...
                "fault_wheel", string(generated.faultWheel), ...
                "fault_type", string(generated.faultType), ...
                "fault_start_s", generated.faultStartSeconds, ...
                "fault_end_s", generated.faultEndSeconds, ...
                "fault_severity", generated.faultSeverity, ...
                "dropout_probability", ...
                    generated.faultDropoutProbability, ...
                "effective_dropout_probability", ...
                    generated.effectiveDropoutProbability, ...
                "dropped_edge_count", droppedEdgeCount);
        end

        function writeTableChunk(~, chunk, outputPath, firstWrite)
            if firstWrite
                writetable(chunk, outputPath);
            else
                writetable(chunk, outputPath, ...
                    WriteMode="append", WriteVariableNames=false);
            end
        end

        function result = appendTable(~, current, addition)
            if isempty(current)
                result = addition;
            else
                result = [current; addition];
            end
        end

        function configPath = writeTemporaryConfig(~, rawConfig)
            configPath = string(tempname) + ".json";
            fileId = fopen(configPath, "w");
            assert(fileId >= 0, ...
                "Impossible de creer la configuration temporaire.");
            closeFile = onCleanup(@()fclose(fileId));
            fwrite(fileId, jsonencode(rawConfig, PrettyPrint=true), "char");
            clear closeFile
        end

        function deleteTemporaryConfig(~, configPath)
            if isfile(configPath)
                delete(configPath);
            end
        end

        function value = uniform(~, stream, lower, upper)
            value = lower + (upper - lower) * rand(stream);
        end

        function value = pick(~, stream, values)
            value = values(randi(stream, numel(values)));
        end
    end
end
